should fix images in readme
WalnutProgramming/room-finder pull request #45
Opened 2021-03-11 20:46 UTC by regexBuster

Images were moved and it messed up the markdown link for the readme file. It now actually shows images in the readme. :)

2021-03-11 22:06 UTC, Aurelius333 requested changes

2021-03-11 22:06 UTC, Aurelius333 commented on README.md
> +![A single, straight hallway with 8 rooms that alternate between the left and right sides. If the image is not appearing, view the docs at https://room-finder.walnut.direct.](docs-copied-files/images
Ben, could you remove the word files?

2021-03-11 22:07 UTC, regexBuster commented on README.md
> +![A single, straight hallway with 8 rooms that alternate between the left and right sides. If the image is not appearing, view the docs at https://room-finder.walnut.direct.](docs-copied-files/images
no :)

2021-06-13 20:11 UTC, Aurelius333 commented
Closing in favor of #55

2021-06-13 20:11 UTC, closed without merging